### ISSUE TITLE
Wafflestats License?

### ISSUE THREAD

**Issue by tiagoamaro** [MisterWil/wafflestats#3]
Hi Mister Will,

What is the wafflestats license?

Currently, if a project has no license, it cannot be modified or distributed but has its source showing on github and can be forked (Sorry for the pull requests).

I don't know what are your plans with Wafflestats, but I would recommend the highly used MIT license.

Good info page for project Licenses: http://choosealicense.com/licenses/

Best regards.

**Comment by MisterWil** [comment]
Hey,

I've left it as no-license for the time being because I'd rather not have
people pull wafflestats, start it up, and then end up "competing" with
myself for people using it. More so, server costs are expensive, and having
it out there could hurt me. I don't really mind people running it for
private use though.

However, I don't mind pulling in updates (pull requests!) like you're doing
because it allows me to pull in changes people make and release them.

Join ##wafflepool on freenode and we can talk about it further if you would
like.

**Comment by tiagoamaro** [comment]
Great :)

I'll consider this issue closed then
